name: feedback_to_github_issue
description: "Wrapper around feedback package, that uploads the feedback to a new github issue."
version: 0.1.0
repository: https://github.com/martinsellergren/feedback_to_github_issue

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.1.0
  github: ^9.24.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
